### ISSUE TITLE
More automation of release process

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/releases#123]
Right now the process is quite well automated, but still has some minor places where user intervention is required.

Due to the nature of our release "train" we will probably always have to have a phased process where each phase follows another, but it would be best if manual intervention is kept to a minimum for:
1. Ease of use
2. Reduce risks of human error

Therefore, I propose to add the following new commands:
* `make initial release="0.x.y"`
  * Creates the initial release file, and points it to the latest `shipyard` commit and sets the `shipyard` stage.
  * Creates a commit and submits it as a pull request

* `make next release="0.x.y"`
  * Advances the stages as necessary in the release file (eg, if the release file is in stage `shipyard`, advance to the next one)
  * Creates a commit and submits it as a pull request

* `make stable release="0.x.y"`
  * Creates a basic file to branch out the stable branch for the release.
  * Creates a commit and submits it as a pull request

All the commands will support (optional) stable branches.
The commands should have appropriate validations to make sure the user isnt doing anything stupid (eg tries to use a stable branch when it hasnt been created yet).

**Comment by mangelajo** [comment]
Sounds like a good improvement :-)

**Comment by mkolesnik** [comment]
After discussion on the automation sync call this week, it was proposed to use the same command for the automation of the release process, e.g. `mkae release`, and the command would identify the release if exists and advance it, or create if it doesnt.

For branching out, it might be possible to identify that the branch doesn't exist and update the file to have it created.

Hence, a possible command could look like `make release version="0.x.y"`

For the case of GA release, if the file doesn't have the branch specified, the next stage (or first stage) would be to create the stable branch.

We could support explicit creation of branches at an earlier release stage by a variable such as `branch="release-0.x"`
