### ISSUE TITLE
When branching the release-xx branch jobs will fail on the repositories.

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/releases#133]
Then because of this, subsequent jobs to continue releasing from the stable branch will fail:
for example: https://github.com/submariner-io/releases/runs/2475115623

```
[releases]$ docker pull quay.io/submariner/lighthouse-agent:release-0.9-c7e4ecd
Error response from daemon: manifest for quay.io/submariner/lighthouse-agent:release-0.9-c7e4ecd not found: manifest unknown: manifest unknown (edited) 
```

On the operator repo we can see (trying to generate a release-0.9-xxxxx image:
```
[submariner-operator]$ docker pull quay.io/submariner/submariner-gateway:release-0.9
Error response from daemon: manifest for quay.io/submariner/submariner-gateway:release-0.9 not found: manifest unknown: manifest unknown (edited) 
```

or in submariner submariner release job https://github.com/submariner-io/submariner/runs/2474614384 failed with:

```
[submariner]$ docker pull quay.io/submariner/submariner-operator:release-0.9
Error response from daemon: manifest for quay.io/submariner/submariner-operator:release-0.9 not found: manifest unknown: manifest unknown

```

Also, all repos fail (https://github.com/submariner-io/submariner-operator/runs/2475360976 )with: 
```

[submariner-operator]$ [cluster2] bash -c curl -Ls https://get.submariner.io | VERSION=release-0.9 DESTDIR=/go/bin bash
Installing subctl version release-0.9
  OS detected:           linux
  Architecture detected: amd64
  Download URL:          https://github.com/submariner-io/submariner-operator/releases/download/subctl-release-0.9/subctl-release-0.9-linux-amd64.tar.xz

Downloading...
curl: (22) The requested URL returned error: 404 
```

I suggest that, on the moment of branching,:
 * we re-tag all the existing devel images as release-0.9 so we unblock the inter-dependencies, then each repo will regenerate that tag with a new one once rebuilt.
 *  we upload subctl release-0.9 (64bit intel linux binary) to the release.

**Comment by mkolesnik** [comment]
This is indeed problematic, however may I suggest a simpler solution of dropping the "post merge E2E" jobs altogether?

It seems they don't give much value, and they usually fail due to issues like this.

I, for one, never seen such a job catch a real bug, just failures dues to some missing images and such.

**Comment by skitt** [comment]
Partially addressed by https://github.com/submariner-io/shipyard/pull/623

**Comment by mkolesnik** [comment]
E2E on merge jobs were dropped a while ago, this shouldn't be a problem any more
