### ISSUE TITLE
Remove Dockerfile.dapper

### ISSUE THREAD

**Issue by skitt** [submariner-io/releases#148]
Following https://github.com/submariner-io/shipyard/pull/573, we would like to get rid of project-specific `Dockerfile.dapper` files.

Depends on https://github.com/submariner-io/shipyard/issues/575

**Comment by mkolesnik** [comment]
Besides `yq` and `gh` which are easily provided by the Dockerfile, there are some critical env variable we need to pass down - https://github.com/submariner-io/releases/blob/devel/Dockerfile.dapper#L6

How would you suggest we pass them without a project specific `Dockerfile.dapper`?

**Comment by skitt** [comment]
> Besides `yq` and `gh` which are easily provided by the Dockerfile, there are some critical env variable we need to pass down - https://github.com/submariner-io/releases/blob/devel/Dockerfile.dapper#L6
> 
> How would you suggest we pass them without a project specific `Dockerfile.dapper`?

For specific projects, if a specific `Dockerfile.dapper` is required then I think that’s fine. The main goal here was to track the removal of those `Dockerfile.dapper` files which _can_ be removed.

**Comment by mkolesnik** [comment]
OK then I think we can keep it on this project, at least until we have a way to pass these env vars differently (Perhaps using https://github.com/submariner-io/shipyard/pull/594 :))
