### ISSUE TITLE
Release process sometimes fails to create pin PRs

### ISSUE THREAD

**Issue by tpantelis** [submariner-io/releases#199]
As seen in [this run](https://github.com/submariner-io/releases/runs/3305139436),

```
[submariner-operator]$ GOPROXY=direct go get github.com/submariner-io/submariner@v0.10.1
verifying github.com/mikefarah/yaml/v2@v2.4.0/go.mod: checksum mismatch
	downloaded: h1:RDklbk79AGWmwhnvt/jBztapEOGDOx6ZbXqjP6csGnQ=
	go.sum:     h1:ahVqZF4n1W4NqwvVnZzC4es67xsW9uR/RRf2RRxieJU=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

https://github.com/submariner-io/releases/pull/193 recently added `GOPROXY=direct` to skip the golang proxy to alleviate an issue where the proxy didn't find the tagged dependency. The prevailing theory is that tag hadn't yet propagated to the proxy after creation. However bypassing the proxy sometimes results in a checksum mismatch for some problematic dependencies.

It seems the best solution is to use the proxy but keep retrying the operation for a period of time.

**Comment by mkolesnik** [comment]
This actually has to do with a 3rd party dependency and not the released library (which is owned by us and is fine), and is somehow related to the use of `GOPROXY=direct`

**Comment by tpantelis** [comment]
> This actually has to do with a 3rd party dependency and not the released library (which is owned by us and is fine), and is somehow related to the use of `GOPROXY=direct`

Right - adding `GOPROXY=direct` to bypass the proxy introduced this issue. That was to fix the original issue where we suspect our new tag hadn't yet propagated to the proxy after creation.  Hence retries were added. Perhaps you have another theory/solution...
