### ISSUE TITLE
Update PRs also update other dependencies

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/releases#200]
PRs to update Submariner-internal versions through the release process also update non-internal dependencies.

For example:

https://github.com/submariner-io/lighthouse/pull/602#pullrequestreview-726983365

And various other examples in:

https://github.com/submariner-io/submariner-operator/pull/1540/files

**Comment by tpantelis** [comment]
This is a side-effect of running `go mod tidy`.  For the example above, it just so happened that a new gomega version was released and the dependabot PR hadn't gotten merged before the release branch was created.

**Comment by skitt** [comment]
Strictly speaking it’s not related to `go mod tidy`; this isn’t “tidying up dependencies”, it’s bumping transitive dependencies to reflect the reality of the dependency tree. Go dependencies signal the minimum version required: before https://github.com/submariner-io/submariner-operator/pull/1540, `submariner-operator` depended on github.com/aws/aws-sdk-go v1.40.7 or later (within the same major version). That PR however bumps cloud-prepare to v0.10.1, and cloud-prepare depends on v1.40.17 or later of the AWS SDK; as a result, the operator also depends on v1.40.17 or later of the AWS SDK, and the dependency in `go.mod` is bumped as a result.

Such changes are inevitable when bumping Go dependencies.

**Comment by skitt** [comment]
Huh, so we can’t use the wonfix label for our own purposes...

**Comment by dfarrell07** [comment]
Thanks for the explanation @skitt!
