### ISSUE TITLE
fail to curl  service in other K8S cluster  for globalNet case

### ISSUE THREAD

**Issue by weizhoublue** [submariner-io/releases#220]
I have two clusters
cluster1: pod cidr  172.20.0.0/16  .  serivce cidr 172.21.0.0/16 . node1 172.110.185.40 . node2 172.110.185.45
cluster2: pod cidr  172.50.0.0/16  .  serivce cidr 172.51.0.0/16 , node3 172.111.185.50

all node is centos8 with kernel 5.9

these two clusters are connected by globalNet mode with virtual net 192.168.0.0/16 , and use the wireguard tunnel

I export an clusterip service nginx on the cluster1 . I try to curl it from cluster2 with the virutal ip (the ip of imported nginx service on cluster2 is 192.168.0.253 ) ,  and  it failed 

I found the packet maybe drop on the node1(gateway node) of cluster1 . because the dmesg shows the wireguard log:
[ 1401.082813] wireguard: submariner: Packet has unallowed src IP (172.111.185.50) from peer 1 (172.111.185.50:4500)

BTW: when I deploy them with non-globalNet mode, everything works well

**Comment by dfarrell07** [comment]
Thanks for the report @weizhouBlue! Maybe @sridhargaddam can help? I'll note from my side that we do have CI that verifies Globalnet with Wireguard: https://github.com/submariner-io/submariner/runs/3616138375?check_suite_focus=true

**Comment by dfarrell07** [comment]
And as @Jaanki mentioned on https://github.com/submariner-io/releases/issues/221#issuecomment-920914299, it would be better to raise these issues on the main submariner-io/submariner repo, as that's where the Globlanet and Wireguard code is maintained.

**Comment by dfarrell07** [comment]
I imagine for @sridhargaddam or other more-relevant experts to help debug, they will want to know:

* What infra is this running on? AWS/GCP/KinD?
* `subctl gather` results (can tar/gzip and directly uploaded to GitHub).

**Comment by weizhoublue** [comment]
thanks for reminding ， I will close it here and  recreate this issue on main repo  , and  append information you mentioned
https://github.com/submariner-io/submariner/issues/1556
