### ISSUE TITLE
Add testing to make sure release version matches deployed version

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/releases#233]
To avoid further breakages such as  #232 we can add tests to make sure the deployed version is the same as what we're releasing.

**Comment by nyechiel** [comment]
@mkolesnik is this something we want to fix before 0.12.0-rc0?

**Comment by mkolesnik** [comment]
This runs in parallel to the versions themselves so doesnt matter if we fix before or after rc0, but ideally this test should go in sometime sooner rather than later as it will help validate the release against "default image" bump problems.

**Comment by nyechiel** [comment]
@mkolesnik is this still relevant?

**Comment by maayanf24** [comment]
close this for now.
