### ISSUE TITLE
Release 0.11.0

### ISSUE THREAD

**Issue by skitt** [submariner-io/releases#241]
This is a tracker bug to synchronise issues blocking 0.11.0 and PRs which _shouldn’t_ be merged before 0.11.0 is released.

This issue should be updated to depend on any blocker, and any PR which is targeted post-0.11.0 should be updated to depend on this issue.

Depends on https://github.com/submariner-io/lighthouse/issues/627
Depends on submariner-io/submariner-operator#1635 (merged, needs to be backported)
Depends on submariner-io/submariner-operator#1618 (needs review)
Depends on open-cluster-management/submariner-addon#209 (addon, needs review)
Depends on submariner-io/submariner-charts#176 (charts, needs review)
Depends on submariner-io/submariner-charts#172 (charts, merged)
Depends on submariner-io/submariner-website#598 (docs)
Depends on submariner-io/submariner-website#601 (docs)
Depends on submariner-io/submariner-website#599 (docs)
Depends on https://github.com/submariner-io/submariner-charts/pull/181

**Comment by aswinsuryan** [comment]
Depends on:  https://github.com/submariner-io/lighthouse/issues/627

**Comment by Jaanki** [comment]
@skitt dependent bot works for triggers in the main comment section only.

**Comment by skitt** [comment]
The release is done and has been announced on submariner-dev and -users.
