### ISSUE TITLE
Release 0.12.0-m3

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/releases#291]
Due to a bug in shipyard, the [m2 release](https://github.com/submariner-io/releases/issues/261) was squashed and the release is now renamed to m3.

Depends on submariner-io/shipyard#701

**Comment by skitt** [comment]
The release artifacts are available on https://github.com/submariner-io/releases/releases/tag/v0.12.0-m3, so from a dependency perspective this is done; closing so that dependent PRs can be merged.
