### ISSUE TITLE
GA releases should use RC images

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/releases#335]
Ideally, the GA release should use the last RC's images and retag them instead of rebuilding them.
This should avoid any code introduced mistakenly after the RC.
This should also minimize any unaccounted change in underlying image layers (eg F35) since the built images are thoroughly tested after each RC.

The subctl binaries have to be rebuilt since they encode version information, but since go dependencies aren't expected to change this should have no consequences for the final binary and besides the version its expected to be exactly the same.

There is a certain risk in missing critical security updates in such cases, but since the images are rebuilt on GA there is a risk of missing breaking changes as well.
Ideally in such cases a new RC can be introduced and tested, but that would delay the GA release.

An alternative is to rebuilt the GA images, but use the commit hashes from the last RC.
This should pick up any security fixes (and possible instabilities) while omitting any changes that were'nt tested on the project.

**Comment by skitt** [comment]
Note that one of our image does include the `subctl` binary now!

**Comment by mkolesnik** [comment]
Good point, that one might need to be rebuilt if we care about the output of `subctl version` in it, but I dont think we do (the image version tag would be correct either way)

**Comment by skitt** [comment]
> Good point, that one might need to be rebuilt if we care about the output of `subctl version` in it, but I dont think we do (the image version tag would be correct either way)

I agree, I don’t think we care about the version, unless we start telling users to run that image directly instead of downloading and installing `subctl` ;-).
