### ISSUE TITLE
Submariner 0.12.1 release

### ISSUE THREAD

**Issue by skitt** [submariner-io/releases#341]
This is the 0.12.1 tracker. Any issues which we want to fix in 0.12.1 (through a backport from the development branch, ideally) should be added to the dependency list.

Depends on https://github.com/submariner-io/shipyard/pull/787
Depends on https://github.com/submariner-io/submariner/pull/1810
Depends on https://github.com/submariner-io/submariner/pull/1783
Depends on https://github.com/submariner-io/submariner/pull/1764
Depends on https://github.com/submariner-io/submariner/pull/1765
Depends on https://github.com/submariner-io/submariner-operator/pull/1986
Depends on https://github.com/submariner-io/cloud-prepare/pull/245
Depends on https://github.com/submariner-io/submariner-operator/issues/1977
Depends on https://github.com/submariner-io/lighthouse/pull/737

**Comment by mkolesnik** [comment]
This was released last week
