### ISSUE TITLE
feat: use an auto changelog generator

### ISSUE THREAD

**Issue by SteveMattar** [submariner-io/releases#36]
consider using [git-chglog](https://github.com/git-chglog/git-chglog)

**Comment by dfarrell07** [comment]
There's some guidance about release notes in the CII best practices we should keep in mind (for https://github.com/submariner-io/submariner/issues/798):

https://bestpractices.coreinfrastructure.org/en/criteria#0.release_notes

**Comment by SteveMattar** [comment]
@dfarrell07 that's an interesting approach - thanks for sharing!
