### ISSUE TITLE
Release creation should use automatic retries

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/releases#360]
When creating the actual release (https://github.com/submariner-io/releases/releases) the CI sometimes fails due to various GH related errors (eg https://github.com/submariner-io/releases/runs/6353959762?check_suite_focus=true#step:3:1224).

We need to have releases code retry the operation a few time in case of failure.

**Comment by nyechiel** [comment]
@mkolesnik @skitt should we backport this to `release-0.13`?
