### ISSUE TITLE
Release 0.12.2

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/releases#363]
This is the 0.12.2 tracker. Any issues which we want to fix in 0.12.2 (through a backport from the development branch, ideally) should be added to the dependency list.

Depends on https://github.com/submariner-io/submariner-operator/pull/2109 (DONE = merged and backported)
Depends on https://github.com/submariner-io/lighthouse/pull/778 (DONE = merged and backported)
Depends on https://github.com/submariner-io/submariner-operator/pull/2107 (DONE = merged and backported)
Depends on https://github.com/submariner-io/cloud-prepare/pull/303 (DONE = merged and backported)
Depends on https://github.com/submariner-io/releases/pull/411 (DONE = merged and backported)
Depends on https://github.com/submariner-io/admiral/pull/377 (DONE = merged and backported)
Depends on https://github.com/submariner-io/submariner-operator/pull/2116 (DONE = merged and backported)
Depends on https://github.com/submariner-io/submariner-operator/pull/2119 (DONE = merged and backported)
Depends on https://github.com/submariner-io/submariner-operator/pull/2117 (DONE = merged and backported)
Depends on https://github.com/submariner-io/shipyard/pull/850 (DONE = merged and backported)
Depends on https://github.com/submariner-io/submariner/pull/1894 (DONE = merged and backported)
Depends on https://github.com/submariner-io/submariner/pull/1895 (DONE = merged and backported)
Depends on https://github.com/submariner-io/submariner-operator/pull/2121 (DONE = merged and backported)
Depends on https://github.com/submariner-io/submariner/pull/1908 (DONE = merged and backported)
Depends on https://github.com/submariner-io/submariner-operator/pull/2128  (DONE = merged and backported)

**Comment by dfarrell07** [comment]
Added https://github.com/submariner-io/lighthouse/pull/715, it's tracked with BZ downstream but is not in release-0.12.

**Comment by dfarrell07** [comment]
This should show the PRs merged to release-0.12 since 0.12.1: https://github.com/pulls?q=is%3Apr+user%3Asubmariner-io+label%3Abackport-handled+created%3A%3E2022-04-24+

**Comment by yboaron** [comment]
@nyechiel @mkolesnik So, based on [this comment](https://github.com/submariner-io/releases/pull/366#issuecomment-1156184737) I assume we can delete [this issue](https://github.com/submariner-io/releases/pull/366) from the dependency list of 0.12.2 , right ?

**Comment by mkolesnik** [comment]
@yboaron make sure to run the release process itself from the `release-0.12` branch on the releases repo, since the process changed in 0.13

**Comment by nyechiel** [comment]
Done: https://github.com/submariner-io/releases/releases/tag/v0.12.2
