### ISSUE TITLE
Release 0.13.1

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/releases#439]
This is a tracker issue to synchronise issues blocking 0.13.1 and PRs which shouldn’t be merged before 0.13.1 is released.

Release notes: https://github.com/submariner-io/submariner-website/pull/825

This issue should be updated to depend on any blocker, and any PR which is targeted post-0.13.1 should be updated to depend on this issue.

Depends on https://github.com/submariner-io/subctl/pull/165
Depends on https://github.com/submariner-io/lighthouse/pull/833
Depends on https://github.com/submariner-io/subctl/pull/179
Depends on https://github.com/submariner-io/subctl/pull/184
Depends on https://github.com/submariner-io/submariner/pull/1953
Depends on https://github.com/submariner-io/submariner-operator/pull/2189
Depends on https://github.com/submariner-io/cloud-prepare/pull/365
Depends on https://github.com/submariner-io/subctl/pull/232
Depends on https://github.com/submariner-io/submariner-operator/pull/2197
Depends on https://github.com/submariner-io/cloud-prepare/pull/388
Depends on https://github.com/submariner-io/submariner/pull/2026
Depends on https://github.com/submariner-io/submariner/pull/1931
Depends on https://github.com/submariner-io/subctl/pull/243

**Comment by dfarrell07** [comment]
Do we want to backported https://github.com/submariner-io/submariner/pull/2019 first?

**Comment by dfarrell07** [comment]
This is done :heavy_check_mark:
