### ISSUE TITLE
Remove https://github.com/submariner-io/ovn-kubernetes once 0.12 is EOL

### ISSUE THREAD

**Issue by skitt** [submariner-io/releases#449]
Since 0.13, we no longer reference https://github.com/submariner-io/ovn-kubernetes; remove it once 0.12 reaches its EOL (with the release of 0.14).

Depends on #448

**Comment by nyechiel** [comment]
@skitt I think this can be done now?

**Comment by skitt** [comment]
The repository has been deleted.
