### ISSUE TITLE
Tests are always being run on stable branches, and always fail

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/releases#654]
The tests are written to be run on the main development branch. we should probably just disable them for stable branches (and maybe just run stable branch specific tests, which need to be invented for this purpose).

**Comment by dfarrell07** [comment]
It looks like release-0.13 doesn't have this issue FYI.

**Comment by dfarrell07** [comment]
The "tests" in question are the `Testing / Entire release process (100.0.0-m0)` and `
Testing / Entire release process (100.0.0-rc0)` jobs FYI. They are failing on on 0.14-release.

**Comment by dfarrell07** [comment]
They don't seem to be running on stable branches anymore: https://github.com/submariner-io/releases/pull/861
