### ISSUE TITLE
Release should retry creating the pull request for updating go dependencies

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/releases#698]
As part of the release process we create PRs to bump released components versions.
Sometimes this process fails (although the PR might get created).

In this case we should have some retry logic (perhaps even try to force delete the PR, because sometimes it gets created in a screwed up state).

**Comment by skitt** [comment]
Some of the failures should be fixed by the recent dependency bumping rework (one PR per project), but it’s still possible for this to fail if `go get` fails for some reason so it would be useful to retry. (The failures addressed by the dependency rework wouldn’t be fixed by retries.)

**Comment by dfarrell07** [comment]
I don't think we've seen this error, or any release issues, in quite a while. Unless we actually see the error, I'm not sure it's worth adding complexity to mitigate it.
