### ISSUE TITLE
The releases projects should have integration tests

### ISSUE THREAD

**Issue by skitt** [submariner-io/releases#704]
It should be possible to run a test release, either periodically or on PRs, to catch errors before we try to actually perform a real release.

**Comment by dfarrell07** [comment]
We talked about the practicality of this and it seemed unsure.

**Comment by dfarrell07** [comment]
This has been discussed quite a few times. We think it's possible but quite difficult and there are alternatives.

* Do a pre release right before the real release
* Scrub the broken release and make a new one
* Dry run has some minor coverage
