### ISSUE TITLE
Automate sending the pull request to update OperatorHub.io

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/releases#76]
This step is still done manually, we can automate it via the release process.

Reference: https://submariner.io/development/release-process/#step-7-update-the-submariner-operator-on-operatorhubio

**Comment by skitt** [comment]
This requires `make bundle` etc. to update the operator first, which should be done as part of the release (_i.e._ the bundles should be correct for the target release in the operator repository before the latter is tagged).

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
There's updated guidance for this upstream, see: https://github.com/operator-framework/community-operators/issues/3883

**Comment by mkolesnik** [comment]
Closing for now as it isnt a priority (our bundle is broken anyhow)

We should revisit this after https://github.com/submariner-io/enhancements/issues/81
